/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 26 00:31:54 SGT 2014
 */

package wox.serial;

import static org.junit.Assert.*;
import org.junit.Test;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;
import wox.serial.Easy;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class Easy_ESTest extends Easy_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 wox.serial.Easy.load(Ljava/lang/String;)Ljava/lang/Object;: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      Object object0 = Easy.load((String) null);
      assertNull(object0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 wox.serial.Easy.<init>()V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      Easy easy0 = new Easy();
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 wox.serial.Easy.save(Ljava/lang/Object;Ljava/lang/String;)V: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      Object object0 = new Object();
      Easy.save(object0, (String) null);
  }
}
