/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Dec 26 00:34:08 SGT 2014
 */

package wox.serial;

import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;

public class SimpleReader_ESTest_scaffolding {

  @org.junit.Rule 
  public org.junit.rules.Timeout globalTimeout = new org.junit.rules.Timeout(6000); 

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 5000);
  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    resetClasses(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
            java.lang.System.setProperty("java.home", "/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre"); 
    java.lang.System.setProperty("user.dir", "/Users/asankhaya/git/wox/java"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/3s/ld4tlz5n01qcqdfgpjqzg2wr0000gn/T/"); 
    java.lang.System.setProperty("awt.toolkit", "sun.lwawt.macosx.LWCToolkit"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.separator", "/"); 
        java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.CGraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.lwawt.macosx.CPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "evosuite.jar:/Users/asankhaya/.m2/repository/org/jdom/jdom2/2.0.5/jdom2-2.0.5.jar:target/classes"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
        java.lang.System.setProperty("java.endorsed.dirs", "/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "/Users/asankhaya/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "Java(TM) SE Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_05-b13"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
        java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_05"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "Java HotSpot(TM) 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.version", "25.5-b02"); 
    java.lang.System.setProperty("line.separator", "\n"); 
    java.lang.System.setProperty("os.arch", "x86_64"); 
    java.lang.System.setProperty("os.name", "Mac OS X"); 
    java.lang.System.setProperty("os.version", "10.10.1"); 
    java.lang.System.setProperty("path.separator", ":"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.home", "/Users/asankhaya"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "asankhaya"); 
    java.lang.System.setProperty("user.timezone", "Asia/Singapore"); 
      }

  private static void initializeClasses() {
    org.evosuite.runtime.ClassStateSupport.initializeClasses(SimpleReader_ESTest_scaffolding.class.getClassLoader() ,
      "org.jdom2.IllegalDataException",
      "org.jdom2.CloneBase",
      "org.jdom2.filter.ElementFilter",
      "wox.serial.Serial",
      "org.jdom2.output.Format$1",
      "org.jdom2.internal.SystemProperty",
      "org.jdom2.Text",
      "org.jdom2.Document",
      "org.jdom2.JDOMException",
      "wox.serial.ObjectReader",
      "org.jdom2.ContentList$CLIterator",
      "org.jdom2.AttributeType",
      "org.jdom2.Verifier",
      "org.jdom2.util.NamespaceStack",
      "org.jdom2.Namespace",
      "wox.serial.SimpleReader",
      "org.jdom2.output.LineSeparator",
      "org.jdom2.output.support.AbstractOutputProcessor",
      "org.jdom2.NamespaceAware",
      "org.jdom2.IllegalTargetException",
      "org.jdom2.output.Format",
      "org.jdom2.output.support.AbstractXMLOutputProcessor",
      "org.jdom2.output.support.XMLOutputProcessor",
      "org.jdom2.output.XMLOutputter$DefaultXMLProcessor",
      "org.jdom2.CDATA",
      "org.jdom2.EntityRef",
      "org.jdom2.output.EscapeStrategy",
      "org.jdom2.AttributeList",
      "org.jdom2.output.Format$EscapeStrategyUTF",
      "org.jdom2.DataConversionException",
      "org.jdom2.Element",
      "wox.serial.EncodeBase64",
      "org.jdom2.DocType",
      "org.jdom2.ProcessingInstruction",
      "wox.serial.Util",
      "org.jdom2.output.support.Walker",
      "org.jdom2.filter.AbstractFilter",
      "org.jdom2.Content$CType",
      "org.jdom2.output.Format$TextMode",
      "org.jdom2.util.IteratorIterable",
      "org.jdom2.IllegalNameException",
      "org.jdom2.AttributeList$ALIterator",
      "org.jdom2.output.support.FormatStack",
      "org.jdom2.output.Format$EscapeStrategy7Bits",
      "org.jdom2.filter.Filter",
      "org.jdom2.Comment",
      "org.jdom2.Parent",
      "org.jdom2.Content",
      "org.jdom2.output.XMLOutputter",
      "org.jdom2.Attribute",
      "wox.serial.TypeMapping",
      "org.jdom2.ContentList",
      "org.jdom2.output.Format$EscapeStrategy8Bits",
      "org.jdom2.IllegalAddException"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.reset.ClassResetter.getInstance().setClassLoader(SimpleReader_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.ClassStateSupport.resetClasses(
      "wox.serial.TypeMapping",
      "wox.serial.SimpleReader",
      "wox.serial.Serial",
      "wox.serial.EncodeBase64",
      "wox.serial.Util",
      "org.jdom2.AttributeType",
      "org.jdom2.Content",
      "org.jdom2.Element",
      "org.jdom2.Namespace",
      "org.jdom2.Verifier",
      "org.jdom2.Content$CType",
      "org.jdom2.ContentList",
      "org.jdom2.IllegalNameException",
      "org.jdom2.Comment",
      "org.jdom2.EntityRef",
      "org.jdom2.Attribute",
      "org.jdom2.Text",
      "org.jdom2.CDATA",
      "org.jdom2.DocType",
      "org.jdom2.filter.AbstractFilter",
      "org.jdom2.filter.ElementFilter",
      "org.jdom2.IllegalDataException",
      "org.jdom2.AttributeList",
      "org.jdom2.ProcessingInstruction",
      "org.jdom2.IllegalTargetException",
      "org.jdom2.output.LineSeparator",
      "org.jdom2.output.Format",
      "org.jdom2.IllegalAddException",
      "org.jdom2.output.support.AbstractXMLOutputProcessor",
      "org.jdom2.output.XMLOutputter",
      "org.jdom2.output.Format$TextMode",
      "org.jdom2.JDOMException",
      "org.jdom2.DataConversionException"
    );
  }
}
