/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 26 00:36:01 SGT 2014
 */

package wox.serial;

import static org.junit.Assert.*;
import org.junit.Test;
import java.io.File;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.jdom2.Element;
import org.junit.runner.RunWith;
import wox.serial.XMLUtil;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class XMLUtil_ESTest extends XMLUtil_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 wox.serial.XMLUtil.generateRandomNo()Ljava/lang/String;: I32 Branch 1 IF_ICMPGE L145 - true
   * 2 wox.serial.XMLUtil.generateRandomNo()Ljava/lang/String;: I32 Branch 1 IF_ICMPGE L145 - false
   */

  @Test
  public void test0()  throws Throwable  {
      String string0 = XMLUtil.generateRandomNo();
      assertEquals("0", string0);
      assertNotNull(string0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 wox.serial.XMLUtil.xmlToElement(Ljava/lang/String;)Lorg/jdom2/Element;: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
      Element element0 = XMLUtil.xmlToElement(";adHi-X$8mq");
      assertNull(element0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 wox.serial.XMLUtil.getXmlElementAsString(Lorg/jdom2/Element;)Ljava/lang/String;: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = XMLUtil.getXmlElementAsString((Element) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 wox.serial.XMLUtil.element2BrowserString(Lorg/jdom2/Element;)Ljava/lang/String;: root-Branch
   */

  @Test
  public void test3()  throws Throwable  {
      try {
        String string0 = XMLUtil.element2BrowserString((Element) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 wox.serial.XMLUtil.element2String(Lorg/jdom2/Element;)Ljava/lang/String;: root-Branch
   */

  @Test
  public void test4()  throws Throwable  {
      try {
        String string0 = XMLUtil.element2String((Element) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 wox.serial.XMLUtil.<init>()V: root-Branch
   */

  @Test
  public void test5()  throws Throwable  {
      XMLUtil xMLUtil0 = new XMLUtil();
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 wox.serial.XMLUtil.convertXmlToString(Ljava/lang/String;)Ljava/lang/String;: root-Branch
   */

  @Test
  public void test6()  throws Throwable  {
      try {
        String string0 = XMLUtil.convertXmlToString((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 wox.serial.XMLUtil.createFile(Lorg/jdom2/Element;Ljava/io/File;)Z: root-Branch
   */

  @Test
  public void test7()  throws Throwable  {
      MockFile mockFile0 = new MockFile(">", "&gt;");
      // Undeclared exception!
      try {
        boolean boolean0 = XMLUtil.createFile((Element) null, (File) mockFile0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 8
  /*
   * 1 covered goal:
   * 1 wox.serial.XMLUtil.disElement(Ljava/lang/Object;)V: root-Branch
   */

  @Test
  public void test8()  throws Throwable  {
      XMLUtil.disElement((Object) null);
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * 1 wox.serial.XMLUtil.disElement(Lorg/jdom2/Element;)V: root-Branch
   */

  @Test
  public void test9()  throws Throwable  {
      try {
        XMLUtil.disElement((Element) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
